// Note: Just #define HELPTEXT would also need trailing slashes...

const char* HELP_TEXT
= _T(
"Swiss-army-knife tool for manipulating User, System and Session environment\n"
"variables in the Win32 Registry.\n"
"\n"
"Usage: winenv [action] [-options...] [varname] [value]\n"
//!!TODO: "Usage: winenv [action] [-options...] [varname] [value] [command [args...]]\n\n"
"\n"
"  actions & parameters:\n"
"\n"	
"	set varname value    	Set variable <varname> to <value>.\n"
"	del varname [value]  	Delete <varname> (or <value> from <varname>).\n"
"	check varname [value]	Is <varname> (or <value>; see -l) set?\n"
"	show [varname]       	Show variable(s) named \"varname*\".\n"
"	notify               	Tell other processes to refresh their env.\n"
"	help (or /? or -h)   	Show help. This is the default action.\n"
"\n"
"  options (Invalid combinations will have undefined results!):\n"
"\n"
"    -n<SELECTOR...> Lookup <varname> at the selected place(s):\n"
"	   U	--> the User namespace (HKCU\\Environment).\n"
"	   S	--> the System namespace (HKLM\\SYSTEM\\CurrentControlSet\n"
"                  	\\Control\\Session Manager\\Environment)\n"
"	   V	--> the Session namespace (HKCU\\Volatile Environment).\n"
"		    This is the default.\n"
//!!TODO: "          E	--> environment of the executed <command>.\n" // becomes default if <command> given
"\n"
"    -s	\"Subvalue\" mode: treat <value> as a substring of <variable>.\n"
"	<variable> is considered a list of substrings separated by\n"
"	the delimiter specified with the -d option. In this mode:\n"
"	1) set adds <value> to <variable> if <value> is not part of it,\n"
"	2) del removes <value> from <variable> if it is part of it,\n"
"	3) check examines if <value> is part of <varname>.\n"
"	These operations are not case-sensitive, and treat '/' and '\\'\n"
"	chars as being equal, unless raw mode is selected with -d.\n"
"    -d[CHAR] Use CHAR as the delimiter for -s.\n"
"	If -d is omitted, ';' will be used.\n"
"	If -d has no CHAR, it will trigger raw substring mode.\n"
"    -a	Append to the previous value of <varname>. (Implies -s.)\n"
"   	(This is the default for -s.)\n"
"    -p	Prepend to the previous value of <varname>. (Implies -s.)\n"
"\n"
"    -x	Set as REG_EXPAND_SZ string (for delayed %var% substitutions).\n"
"	Or: check -x will prevent auto-expanding the value of <varname>.\n"
"\n"
"    -!	Also do 'notify' after 'set' or 'del'.\n"
"\n"
"    -e	Show examples.\n"
"\n"	
"Return Values:\n"
"\n"
"    0	Success (or 'VALUE FOUND' by 'check').\n"
"    1	'VALUE NOT FOUND' by 'check'.\n"
"    2	Unspecified error. (Error messages go to stderr.)\n"
"    5	Access denied.\n"
"\n"
"Notes:\n"
"	- Multiple -options can be combined into one -optionlist sequence.\n"
"	- The U, S, V modifiers can be freely combined.\n"
"	- 'Check -s' with <value> missing will return 'VALUE FOUND'.\n"
"	- Calling from the CMD shell, use the \"^%SOMEVAR^%\" escape\n"
"	  syntax (or \"%%SOMEVAR%%\" from batch files) to allow setting\n"
"	  auto-expanding (\"REG_EXPAND_SZ\") values with -x.\n"
"	- The 'set' action will create the variable, if necessary.\n"
"	- Use double quotes around any value which contains spaces.\n"
"\n"
"!!!NOTE NOTE NOTE NOTE NOTE!!!\n"
"   - The 'check' action and the -d option are not implemented yet!\n"
"   - The -s (and some) other options do not quite follow the above rules!\n"
"!!!NOTE NOTE NOTE NOTE NOTE!!!\n"
);


const char* EXAMPLES_TEXT
= _T(
"Examples:\n"
"winenv set -nU INSTALLPATH C:\\SetEnv \n"
"	Set the User variable INSTALLPATH to \"C:\\SetEnv\".\n"
"\n"
"winenv set -nS MEDIA C:\\Media \n"
"	Sets the System variable MEDIA to \"C:\\Media\".\n"
"\n"
"winenv set -sp PATH D:\\Bin \n"
"	Prepends \"D:\\Bin\" to the PATH.\n"
"\n"
"winenv set PATH \"D:\\Bin;%PATH%\"\n"
"	Ditto, but does not check & prevent duplicate D:\\Bin.\n"
"\n"
//!!"winenv -a MUSIC ~MEDIA~\\Music \n\tSets the value of MUSIC to be ALWAYS equal to the value of MEDIA\\Music,\n"
//!!"\teven if the value of MEDIA changes, so MUSIC becomes \"C:\\Media\\Music\".\n"
//!!"\tIf MEDIA becomes \"D:\\Media\" then MUSIC becomes \"D:\\Media\\Music\", etc.\n"
);
